PET_TYPE_CHOICES = [
    ('dog', 'Dog🐕'),
    ('cat', 'Cat'),
    ('rabbit', 'Rabbit'),
    ('fish', 'Fish'),
    ('horse', 'Horse'),
    ('hamster', 'Hamster'),
]
GENDER_CHOICES = [
    ('male', 'Male'),
    ('female', 'Female'),
    ('neutral', 'Gender Neutral'),
]
COLOR_CHOICES = [
    ('black', 'Black'),
    ('white', 'White'),
    ('brown', 'Brown'),
    ('gray', 'Gray'),
    ('red', 'Red'),
    ('orange', 'Orange'),
    ('yellow', 'Yellow'),
    ('green', 'Green'),
    ('blue', 'Blue'),
    ('purple', 'Purple'),
    ('pink', 'Pink'),
    ('multicolor', 'Multicolor'),
]
PERSONALITY_TRAITS_CHOICES = [
    ('friendly', 'Friendly'),
    ('playful', 'Playful'),
    ('energetic', 'Energetic'),
    ('intelligent', 'Intelligent'),
    ('loyal', 'Loyal'),
    ('curious', 'Curious'),
    ('affectionate', 'Affectionate'),
    ('independent', 'Independent'),
    ('calm', 'Calm'),
    ('protective', 'Protective'),
]
ORIGIN_CHOICES = [
    ('English', 'English'),
    ('African', 'African'),
    ('Alaskan', 'Alaskan'),
    ('American', 'American'),
    ('Chinese', 'Chinese'),
    ('Hebrew', 'Hebrew'),
    ('Latin', 'Latin'),
    ('Hindu', 'Hindu'),
    ('Mexican', 'Mexican'),
    ('Eskimo', 'Eskimo'),
    ('Hispanic', 'Hispanic'),
    ('Native American', 'Native American'),
    ('Arabic', 'Arabic'),
    ('French', 'French'),
    ('Indian', 'Indian'),
    ('Australian', 'Australian'),
    ('German', 'German'),
    ('Irish', 'Irish'),
    ('Scottish', 'Scottish'),
    ('Biblical', 'Biblical'),
    ('Greek', 'Greek'),
    ('Italian', 'Italian'),
    ('Spanish', 'Spanish'),
    ('Celtic', 'Celtic'),
    ('Hawaiian', 'Hawaiian'),
    ('Japanese', 'Japanese')
]
HISTORICAL_THEMES_CHOICES = [
    ('none', 'None'),
    ('ancient egypt', 'Ancient Egypt'),
    ('medieval europe', 'Medieval Europe'),
    ('renaissance italy', 'Renaissance Italy'),
    ('wild west', 'Wild West'),
    ('ancient china', 'Ancient China'),
    ('ancient greece and Rome', 'Ancient Greece and Rome'),
]
